ENV:
    DEV:
        DEBUG: True
        SQLALCHEMY_DATABASE_URI: 'mysql://root:123456@127.0.0.1/newmax'



CELERY_CONFIG:
    BROKER_URL: 'redis://127.0.0.1:6379/3'





CACHE_CONFIG:
    CACHE_TYPE: 'redis'
    CACHE_REDIS_HOST: '127.0.0.1'
    CACHE_REDIS_DB: 2

